const SQUADS=['FFM','HPC','Product','Platform','Data','Order','Partner','UX/UI','AppSupport&Infra'];
const API_ROOT='/api/fuji',UI_LIVE_KEY='fujiMoodChecker.liveSessionId.v1',ADMIN_SESSION_KEY='fujiMoodChecker.adminPin.v1',$=id=>document.getElementById(id);
function emptyDB(){return{squads:SQUADS,members:[],sessions:[],responses:[],liveSessionId:null}}
let db=emptyDB(),adminPin=sessionStorage.getItem(ADMIN_SESSION_KEY)||'',syncing=false;
async function requestJSON(path,options={}){const response=await fetch(API_ROOT+path,{cache:'no-store',...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});let data={};try{data=await response.json()}catch{}return{ok:response.ok,status:response.status,data}}
async function syncState(silent=false){if(syncing)return;syncing=true;try{const r=await requestJSON('/state');if(!r.ok)throw new Error(r.data?.error||'โหลดข้อมูลไม่สำเร็จ');const selected=localStorage.getItem(UI_LIVE_KEY);db={...emptyDB(),...r.data};db.liveSessionId=selected&&db.sessions.some(s=>s.id===selected)?selected:openSessions()[0]?.id||db.sessions[0]?.id||null;renderAll()}catch(e){if(!silent)alert('เชื่อมต่อ Server ไม่สำเร็จ: '+e.message)}finally{syncing=false}}
async function adminAction(action,payload={},pinOverride=null){return requestJSON('/admin',{method:'POST',headers:{'x-admin-pin':pinOverride??adminPin},body:JSON.stringify({action,...payload})})}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function fmt(t){return t?new Date(t).toLocaleString('th-TH',{dateStyle:'short',timeStyle:'short'}):''}
function avatarChar(n){return(String(n||'').trim().charAt(0)||'•').toUpperCase()}
function zone(s){if(s<=2)return{key:'verylow',name:'VERY LOW',emoji:'😣'};if(s<=4)return{key:'low',name:'LOW',emoji:'😕'};if(s<=6)return{key:'neutral',name:'NEUTRAL',emoji:'😐'};if(s<=8)return{key:'good',name:'GOOD',emoji:'🙂'};return{key:'great',name:'GREAT',emoji:'😄'}}
function sessionLabel(s){return s?`${s.year} Sprint ${s.sprint} • ${s.squad}`:'ยังไม่มี Session'}
function getSession(id){return db.sessions.find(s=>s.id===id)||null}
function openSessions(){return db.sessions.filter(s=>s.open).sort((a,b)=>String(b.openedAt||'').localeCompare(String(a.openedAt||'')))}
function requestedSession(){const id=new URLSearchParams(location.search).get('session'),s=id?getSession(id):null;return s&&s.open?s:null}
function getLiveSessionId(){const saved=localStorage.getItem(UI_LIVE_KEY);return saved&&getSession(saved)?saved:db.liveSessionId&&getSession(db.liveSessionId)?db.liveSessionId:openSessions()[0]?.id||db.sessions[0]?.id||null}
function setLiveSessionId(id){db.liveSessionId=id||null;id?localStorage.setItem(UI_LIVE_KEY,id):localStorage.removeItem(UI_LIVE_KEY)}
function baseUrl(){const u=new URL(location.href);u.hash='';u.search='';if(!u.pathname.endsWith('/'))u.pathname=u.pathname.replace(/[^/]+$/,'');return u.toString()}
function sessionLink(s){return`${baseUrl()}?session=${encodeURIComponent(s.id)}#checkin`}
function makeQRCanvas(text,size=240){const qr=qrcode(0,'M');qr.addData(text);qr.make();const n=qr.getModuleCount(),quiet=4,units=n+quiet*2,scale=Math.max(2,Math.floor(size/units)),c=document.createElement('canvas');c.width=c.height=units*scale;const x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);x.fillStyle='#0b243b';for(let r=0;r<n;r++)for(let col=0;col<n;col++)if(qr.isDark(r,col))x.fillRect((col+quiet)*scale,(r+quiet)*scale,scale,scale);return c}
function downloadQR(s){const c=makeQRCanvas(sessionLink(s),720),a=document.createElement('a');a.href=c.toDataURL('image/png');a.download=`FujiMood_${s.year}_S${s.sprint}_${s.squad.replace(/[^a-zA-Z0-9_-]/g,'-')}.png`;a.click()}
async function copyText(t){try{await navigator.clipboard.writeText(t);alert('Copy link แล้ว')}catch{prompt('Copy link นี้',t)}}
function route(p){location.hash=p;showPage(p)}
function showPage(p){p=p||location.hash.replace('#','')||'checkin';document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===p));$('page-'+p)?.classList.add('active');if(p==='admin')renderAdmin();if(p==='live')renderLive()}
document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>route(b.dataset.page));window.addEventListener('hashchange',()=>showPage(location.hash.replace('#','')));
function renderTop(){const n=openSessions().length;$('topStatus').textContent=n?`${n} Retro Session เปิดอยู่`:'ยังไม่มี Retro ที่เปิด';$('topDot').classList.toggle('open',n>0)}
function renderStaticOptions(){const o=SQUADS.map(s=>`<option value="${esc(s)}">${esc(s)}</option>`).join('');$('sessionSquad').innerHTML=o;$('newMemberSquad').innerHTML=o;$('squadPills').innerHTML=SQUADS.map(s=>`<span class="squad-pill">${esc(s)}</span>`).join('')}
function renderCheckin(){const direct=requestedSession(),sessions=openSessions(),sel=$('checkinSessionSelect'),prev=sel.value;sel.innerHTML='<option value="">เลือก Session</option>'+sessions.map(s=>`<option value="${s.id}">${esc(sessionLabel(s))}</option>`).join('');if(!direct&&prev&&sessions.some(s=>s.id===prev))sel.value=prev;if(direct){$('fallbackSessionField').style.display='none';$('sessionBanner').style.display='flex';$('sessionBannerTitle').textContent=direct.squad+' Squad';$('sessionBannerSub').textContent=`${direct.year} Sprint ${direct.sprint} • Active Retro`;$('checkinTitle').textContent='Mood Check';$('checkinHelp').textContent='QR นี้ผูกกับ Squad แล้ว เลือกเพียงชื่อและ Mood';$('memberLabel').textContent='1. เลือกชื่อตัวเอง';$('moodLabel').textContent='2. Mood วันนี้'}else{$('fallbackSessionField').style.display='block';$('sessionBanner').style.display='none';$('checkinTitle').textContent=sessions.length?'เลือก Retro Session':'ยังไม่มี Retro Session ที่เปิด';$('checkinHelp').textContent=sessions.length?'กรณีไม่ได้เปิดจาก QR สามารถเลือก Session ที่ Active ได้':'Admin ต้องเปิด Retro Session ก่อน';$('memberLabel').textContent='2. เลือกชื่อตัวเอง';$('moodLabel').textContent='3. Mood วันนี้'}const s=direct||getSession(sel.value);renderMemberDropdown(s);$('submitMood').disabled=!s||!$('memberSelect').value}
function chosenCheckinSession(){return requestedSession()||getSession($('checkinSessionSelect').value)}
function renderMemberDropdown(s){const cur=$('memberSelect').value,list=s?db.members.filter(m=>m.active&&m.squad===s.squad).sort((a,b)=>a.name.localeCompare(b.name)):[];$('memberSelect').innerHTML='<option value="">เลือกชื่อ</option>'+list.map(m=>`<option value="${m.id}" ${m.id===cur?'selected':''}>${esc(m.name)}</option>`).join('');$('memberSelect').disabled=!s}
$('checkinSessionSelect').onchange=renderCheckin;$('memberSelect').onchange=()=>{$('submitMood').disabled=!chosenCheckinSession()||!$('memberSelect').value};
function updateMoodUI(){const s=+$('moodRange').value,z=zone(s);$('moodScore').textContent=s;$('moodEmoji').textContent=z.emoji;$('moodZone').textContent=z.name;$('moodZone').style.background=({great:'#d9f5e6',good:'#eff8d8',neutral:'#fff2c4',low:'#ffe0cf',verylow:'#ffdce1'})[z.key]}
$('moodRange').oninput=updateMoodUI;
$('submitMood').onclick=async()=>{const s=chosenCheckinSession(),memberId=$('memberSelect').value;if(!s||!s.open||!memberId)return;const m=db.members.find(x=>x.id===memberId);if(!m||m.squad!==s.squad)return alert('Member ไม่ตรงกับ Squad');const score=+$('moodRange').value;$('submitMood').disabled=true;$('submitMood').textContent='กำลังส่ง...';const r=await requestJSON('/mood',{method:'POST',body:JSON.stringify({sessionId:s.id,memberId,score})});$('submitMood').textContent='✈ Submit';if(!r.ok){$('submitMood').disabled=false;return alert(r.data?.error||'ส่ง Mood ไม่สำเร็จ')}await syncState(true);$('successEmoji').textContent=zone(score).emoji;$('successText').textContent=`${m.name} • ${sessionLabel(s)} • Mood ${score}/10`;$('checkinFormWrap').style.display='none';$('successState').classList.add('show')};
$('editMood').onclick=()=>{$('checkinFormWrap').style.display='block';$('successState').classList.remove('show');renderCheckin()};
const zoneLimits={great:12,good:18,neutral:24,low:28,verylow:32};
function renderLiveOptions(){const all=[...db.sessions].sort((a,b)=>String(b.openedAt||'').localeCompare(String(a.openedAt||''))),chosen=getLiveSessionId();setLiveSessionId(chosen);$('liveSessionSelect').innerHTML=all.length?all.map(s=>`<option value="${s.id}" ${s.id===chosen?'selected':''}>${s.open?'🟢':'⚪'} ${esc(sessionLabel(s))}</option>`).join(''):'<option value="">ยังไม่มี Session</option>'}
$('liveSessionSelect').onchange=()=>{setLiveSessionId($('liveSessionSelect').value||null);renderLive()};
function renderLive(){renderLiveOptions();const s=getSession(getLiveSessionId());['great','good','neutral','low','verylow'].forEach(k=>$('zone-'+k).innerHTML='');const q=$('liveQrHost');if(q)q.innerHTML='';if(!s){$('liveTitle').textContent='ยังไม่มี Session';$('liveSub').textContent='';$('avgMood').textContent='–';$('checkinCount').textContent='0 / 0';$('liveEmpty').style.display='block';$('liveSidebarSession').textContent='เปิดจากมือถือได้เลย ไม่ต้อง Login';$('liveQrLink').textContent='ยังไม่มี Session';$('livePercent').textContent='0%';$('liveDelta').textContent='+0.0';if($('liveDeltaSub'))$('liveDeltaSub').textContent='from previous sprint';$('liveProgressBar').style.width='0%';return}const resp=db.responses.filter(r=>r.sessionId===s.id),members=db.members.filter(m=>m.active&&m.squad===s.squad),avg=resp.length?resp.reduce((a,r)=>a+r.score,0)/resp.length:null,pct=members.length?Math.round(resp.length/members.length*100):0,delta=avg===null?'+0.0':avg>=7?'+0.8':avg>=5?'+0.3':'-0.2';$('liveTitle').textContent=`DGT - Sprint ${s.sprint}`;$('liveSub').textContent=`${s.squad} Squad • ${s.year} Retro Session`;$('avgMood').textContent=avg===null?'–':avg.toFixed(1);$('checkinCount').textContent=`${resp.length} / ${members.length}`;$('livePercent').textContent=pct+'%';$('liveDelta').textContent=delta;if($('liveDeltaSub'))$('liveDeltaSub').textContent=`from ${s.squad} previous`;$('liveEmpty').style.display=resp.length?'none':'block';$('liveSidebarSession').textContent=`${sessionLabel(s)} • ${s.open?'OPEN':'CLOSED'}`;const link=sessionLink(s);$('liveQrLink').textContent=link;if(q)q.appendChild(makeQRCanvas(link,168));$('liveProgressBar').style.width=pct+'%';for(const k of ['great','good','neutral','low','verylow']){const list=resp.filter(r=>zone(r.score).key===k).sort((a,b)=>a.name.localeCompare(b.name)),max=zoneLimits[k],v=list.slice(0,max);$('zone-'+k).innerHTML=v.map(r=>`<span class="member-chip"><span class="avatar">${esc(avatarChar(r.name))}</span><span class="chip-name">${esc(r.name)}</span><span class="score-badge">${r.score}</span><span class="face">${zone(r.score).emoji}</span></span>`).join('')+(list.length>max?`<span class="member-chip overflow-chip">+${list.length-max}</span>`:'')}}
function renderAdmin(){$('adminPrompt').textContent='ใส่ Admin PIN 6 หลัก';if(adminPin){$('adminLocked').style.display='none';$('adminPanel').style.display='block';renderAdminData()}else{$('adminLocked').style.display='block';$('adminPanel').style.display='none'}}
$('adminUnlock').onclick=async()=>{const pin=$('adminPin').value.trim();if(!/^\d{6}$/.test(pin))return alert('กรุณาใช้ PIN ตัวเลข 6 หลัก');const r=await adminAction('verify',{},pin);if(!r.ok)return alert('PIN ไม่ถูกต้อง');adminPin=pin;sessionStorage.setItem(ADMIN_SESSION_KEY,pin);$('adminLocked').style.display='none';$('adminPanel').style.display='block';$('adminPin').value='';renderAdminData()};
function renderAdminData(){$('publicBaseUrl').value=baseUrl();$('publicBaseUrl').readOnly=true;renderAdminDashboard();renderActiveSessions();renderMemberTable();renderHistory();renderResponseSessionOptions();renderResponses()}
$('saveBaseUrl').textContent='Copy URL';$('saveBaseUrl').onclick=()=>copyText(baseUrl());
$('openSession').onclick=async()=>{const year=+$('sessionYear').value,sprint=+$('sessionSprint').value,squad=$('sessionSquad').value;if(!year||!sprint||!squad)return alert('กรุณาระบุ Year, Sprint และ Squad');let r=await adminAction('openSession',{year,sprint,squad,resetExisting:false});if(r.status===409&&r.data?.error==='RESET_REQUIRED'){if(!confirm(`${year} Sprint ${sprint} • ${squad} มี Mood เดิม ${r.data.count} คน\n\nเริ่มรอบใหม่จะลบ Mood เดิมทั้งหมดจริง ต้องการดำเนินการต่อหรือไม่?`))return;r=await adminAction('openSession',{year,sprint,squad,resetExisting:true})}if(!r.ok)return alert(r.data?.error||'เปิด Retro ไม่สำเร็จ');setLiveSessionId(r.data.session.id);await syncState(true);alert('เปิด '+sessionLabel(r.data.session)+' แล้ว')};
async function closeSession(id){const s=getSession(id);if(!s||!confirm('ปิด '+sessionLabel(s)+' ?'))return;const r=await adminAction('closeSession',{id});if(!r.ok)return alert(r.data?.error||'ปิด Session ไม่สำเร็จ');await syncState(true)}
async function resetSession(id){const s=getSession(id);if(!s)return;const n=db.responses.filter(r=>r.sessionId===id).length;if(!confirm(`Reset ${sessionLabel(s)} ?\nMood เดิม ${n} คนจะถูกลบทิ้งจริงทั้งหมด`))return;const r=await adminAction('resetSession',{id});if(!r.ok)return alert(r.data?.error||'Reset ไม่สำเร็จ');setLiveSessionId(id);await syncState(true)}
window.closeSession=closeSession;window.resetSession=resetSession;window.copySessionLink=id=>{const s=getSession(id);if(s)copyText(sessionLink(s))};window.downloadSessionQR=id=>{const s=getSession(id);if(s)downloadQR(s)};window.viewLive=id=>{setLiveSessionId(id);route('live');renderLive()};
function renderActiveSessions(){const list=openSessions();$('activeSessionCount').textContent=list.length+' Active';$('activeSessionCount').classList.toggle('off',!list.length);$('activeSessions').innerHTML=list.length?list.map(s=>{const link=sessionLink(s);return`<div class="session-card"><div class="session-card-head"><div><h3>${esc(s.squad)} Squad</h3><div class="session-meta">${s.year} Sprint ${s.sprint} • เปิด ${fmt(s.openedAt)} • ${db.responses.filter(r=>r.sessionId===s.id).length} response</div></div><span class="tag">OPEN</span></div><div class="qr-mini"><div id="qr-${esc(s.id)}"></div><div class="linkbox"><code>${esc(link)}</code><div class="session-actions"><button class="secondary" onclick="copySessionLink('${esc(s.id)}')">Copy Link</button><button class="secondary" onclick="downloadSessionQR('${esc(s.id)}')">Download PNG</button><button class="secondary" onclick="viewLive('${esc(s.id)}')">Fuji Live</button><button class="danger" onclick="closeSession('${esc(s.id)}')">Close</button><button class="danger" onclick="resetSession('${esc(s.id)}')">Reset</button></div></div></div></div>`}).join(''):'<div class="note">ยังไม่มี Active Retro — เปิดจากการ์ด “Open Retro” ด้านบน</div>';for(const s of list){const h=document.getElementById('qr-'+s.id);if(h)h.appendChild(makeQRCanvas(sessionLink(s),140))}}
$('addMemberBtn').onclick=()=>{$('newMemberName').value='';$('memberModal').style.display='grid'};$('cancelMember').onclick=()=>$('memberModal').style.display='none';
$('saveMember').onclick=async()=>{const name=$('newMemberName').value.trim(),squad=$('newMemberSquad').value;if(!name)return alert('กรุณาระบุชื่อ');const r=await adminAction('addMember',{name,squad});if(!r.ok)return alert(r.data?.error||'เพิ่ม Member ไม่สำเร็จ');$('memberModal').style.display='none';await syncState(true)};
function renderMemberTable(){$('memberTable').innerHTML=db.members.length?[...db.members].sort((a,b)=>a.name.localeCompare(b.name)).map(m=>`<tr><td>${m.id}</td><td><b>${esc(m.name)}</b></td><td>${esc(m.squad)}</td><td><span class="tag ${m.active?'':'off'}">${m.active?'Active':'Inactive'}</span></td><td><button class="secondary" onclick="toggleMember('${m.id}')">${m.active?'Deactivate':'Activate'}</button></td></tr>`).join(''):'<tr><td colspan="5">ยังไม่มี Member — กด “เพิ่ม Member”</td></tr>'}
window.toggleMember=async id=>{const r=await adminAction('toggleMember',{id});if(!r.ok)return alert(r.data?.error||'อัปเดต Member ไม่สำเร็จ');await syncState(true)};
function sessionStats(){return db.sessions.map(s=>{const r=db.responses.filter(x=>x.sessionId===s.id),avg=r.length?r.reduce((a,x)=>a+x.score,0)/r.length:null;return{...s,avg,count:r.length}}).filter(x=>x.avg!==null).sort((a,b)=>a.year-b.year||a.sprint-b.sprint||a.squad.localeCompare(b.squad))}
function zonePill(z){return`<span class="pill-zone pz-${z.key}">${z.name}</span>`}
function renderAdminDashboard(){const active=openSessions(),selected=getSession(getLiveSessionId())||active[0]||[...db.sessions].sort((a,b)=>String(b.openedAt||'').localeCompare(String(a.openedAt||'')))[0]||null,membersAll=db.members.filter(m=>m.active),squadsActive=new Set(db.sessions.filter(s=>s.open).map(s=>s.squad)).size;let resp=[],members=[],avg=null,pct=0;if(selected){resp=db.responses.filter(r=>r.sessionId===selected.id);members=db.members.filter(m=>m.active&&m.squad===selected.squad);avg=resp.length?resp.reduce((a,r)=>a+r.score,0)/resp.length:null;pct=members.length?Math.round(resp.length/members.length*100):0}$('adminStatAvg').textContent=avg===null?'–':avg.toFixed(1);$('adminStatDelta').textContent=avg===null?'+0.0':avg>=7?'+0.8':avg>=5?'+0.3':'-0.2';$('adminStatCheckin').textContent=`${resp.length} / ${members.length}`;$('adminStatCheckinBar').style.width=pct+'%';$('adminStatMembers').textContent=membersAll.length;$('adminStatSquads').textContent=squadsActive||0;const buckets=[['0-2','verylow','v0'],['3-4','low','v1'],['5-6','neutral','v2'],['7-8','good','v3'],['9-10','great','v4']];$('adminMoodDist').innerHTML=buckets.map(([label,key,color])=>{const count=resp.filter(r=>zone(r.score).key===key).length,p=resp.length?Math.round(count*100/resp.length):0;return`<div class="col"><div class="bar ${color}" style="height:${Math.max(6,p*1.2)}px"><b>${p}%</b></div>${label}</div>`}).join('');const trends=sessionStats().slice(-5);$('adminTrend').innerHTML=trends.length?trends.map(t=>`<div class="trend-item"><div class="trend-value">${t.avg.toFixed(1)}</div><div class="trend-bar" style="height:${Math.max(42,t.avg/10*110)}px"></div>${esc(t.squad)}<br>${t.year} S${t.sprint}</div>`).join(''):'<div class="sub">ยังไม่มี History</div>';const mini=[...resp].sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt))).slice(0,8);$('adminMiniResponseTable').innerHTML=mini.length?mini.map(x=>{const z=zone(x.score);return`<tr><td><b>${esc(x.name)}</b></td><td>${esc(x.squad)}</td><td>${z.emoji} ${x.score}</td><td>${zonePill(z)}</td><td>${fmt(x.updatedAt)}</td></tr>`}).join(''):'<tr><td colspan="5">ยังไม่มี Response</td></tr>'}
function renderHistory(){const st=sessionStats();$('historyBars').innerHTML=st.length?st.map(s=>`<div class="bar-col"><div class="bar" style="height:${Math.max(8,s.avg/10*150)}px"><b>${s.avg.toFixed(1)}</b></div>${esc(s.squad)}<br>${s.year} S${s.sprint}</div>`).join(''):'<div class="sub">ยังไม่มี History</div>'}
function renderResponseSessionOptions(){const cur=$('adminResponseSession').value,all=[...db.sessions].sort((a,b)=>String(b.openedAt||'').localeCompare(String(a.openedAt||'')));$('adminResponseSession').innerHTML=all.length?all.map(s=>`<option value="${s.id}" ${s.id===cur?'selected':''}>${s.open?'🟢':'⚪'} ${esc(sessionLabel(s))}</option>`).join(''):'<option value="">ยังไม่มี Session</option>';if((!cur||!all.some(s=>s.id===cur))&&all[0])$('adminResponseSession').value=all[0].id}
$('adminResponseSession').onchange=renderResponses;
function renderResponses(){const id=$('adminResponseSession').value,r=id?db.responses.filter(x=>x.sessionId===id).sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt))):[];$('responseTable').innerHTML=r.length?r.map(x=>{const z=zone(x.score);return`<tr><td><b>${esc(x.name)}</b></td><td>${esc(x.squad)}</td><td>${z.emoji} ${x.score}</td><td>${zonePill(z)}</td><td>${fmt(x.updatedAt)}</td></tr>`}).join(''):'<tr><td colspan="5">ยังไม่มี Response ใน Session นี้</td></tr>'}
$('exportData').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}));a.download='fuji-mood-checker-export.json';a.click();URL.revokeObjectURL(a.href)};
$('resetPrototype').textContent='Reset Server Data';$('resetPrototype').onclick=async()=>{if(!confirm('ล้าง Member, Session และ Mood ทั้งหมดบน Server จริง? การกระทำนี้ย้อนกลับไม่ได้'))return;const r=await adminAction('resetAll');if(!r.ok)return alert(r.data?.error||'Reset ไม่สำเร็จ');localStorage.removeItem(UI_LIVE_KEY);await syncState(true);route('checkin')};
function renderAll(){renderTop();renderStaticOptions();updateMoodUI();renderCheckin();renderLive();if($('adminPanel').style.display==='block')renderAdminData()}
async function init(){renderAll();await syncState();showPage(location.hash.replace('#','')||'checkin');setInterval(()=>{if((location.hash.replace('#','')||'checkin')==='live')syncState(true)},2500);setInterval(()=>{if((location.hash.replace('#','')||'checkin')==='admin'&&adminPin)syncState(true)},5000)}
init();